### ISSUE TITLE
Work with connection sources

### ISSUE THREAD

**Issue by liborpolansky** [roadrunnerlenny/etlbox#10]
Hi,
I have a question regarding work with the more than one db connections in ETL box.

I need 3 connections in ETL process:
1) source db connection - to export data from the source db
2) destination db connection (this is not the same db server connection as is source)
3) db for log tables - I can't log to the same db as destination db  

Could you describe me the sequence of steps how I should use it in the controlflow, dataflow together with the logging? It is not clear to me how to use the connections when I use multiple db server connections at the same time.

I try to transfer data from one SQL server to another one.

SQL server A (source DB) -> transformation flow -> SQL server B (destination DB)
all mentioned 3 steps/tasks are logging to log DB

log DB contains tables and procedures created by CreateLogTablesTask.CreateLog()

I need more information how to use/set/share  DbConnection in the proces of ControlFlow and DataFlow. Do I need to set up a connection at every step of etl again and again?

For DB logging connection I found ControlFlow.SetLoggingDatabase property but I'm not sure when to set it in the ETL process flow. Just at the beginning of ETL in Log.Start()? Is loggingDatabase setting independent of the settings in the ControlFlow.CurrentDbConnection method?

Thank you

**Comment by roadrunnerlenny** [comment]
Hi, 
Thanks again for your question. This is a good one, and I see again that the documentation is missing examples here. But let me assure you that I designed the framework having in mind that data needs to be transferred over DB or Server borders. 
The idea in ETLBox is that every object (ControlFlow and Dataflow) always extend GenericTask which has a ConnectionManager property. Basically the idea is that you pass them a ConnectionManager object when instantiating it which is then used to get the right DB.
Your question is very specific, so let me create an example for this case (and also add a test case) that demonstrates the usage. I saw that there could still be a smaller flaw in DBSource with this approach,  so I would like to get back to you providing you the example and having all bugs fixed as soon as possible.

**Comment by roadrunnerlenny** [comment]
Sorry for the delay coming back to you.
I was able to fix two minor bugs, and prepare two cases that demonstrate the use of the ConnectionManager to transfer data across databases.
 I also updated the documentation: (https://etlbox.net/articles/example_different_dbs.html)

Here are the two test cases that I added and demonstrate how to use the different Connections:
1)
https://github.com/roadrunnerlenny/etlbox/blob/004638a38889a124fd3499f2fd003a328947ab97/ETLBoxTest/src/DataFlow/TestDataFlowDifferentDBs.cs#L53-L81

2)
https://github.com/roadrunnerlenny/etlbox/blob/004638a38889a124fd3499f2fd003a328947ab97/ETLBoxTest/src/DataFlow/TestDataFlowDifferentDBs.cs#L83-L136

I hope this clarify how you can use a ConnectionManager with a DBSource or DBDestination.
Please note that there won`t be any downside either by always creating a new ConnectionManager object or by reusing them. Internally, there will be always a new connection object created - Connection Pooling and Management is done by ADO.NET, which internally takes care if the connection really is released or kept to work more performant.

If you have any suggestions or comments feel free to post them, you feedback is very appreciated.

**Comment by roadrunnerlenny** [comment]
Please make sure to download the latest version (1.2.2) - I just released a new version on nuget. (https://www.nuget.org/packages/ETLBox/1.2.2)
The example above will only work with this version.
