### ISSUE TITLE
Show progress

### ISSUE THREAD

**Issue by dquinter** [roadrunnerlenny/etlbox#11]
Hi Andreas, thans for this marvelous library.

I have a question and maybe you can help me. Is it possible to show some feedback to the user? Something like showing the progress every n records?

Example:
** INFORMATION ** Rows inserted: 1,000. Loading continues... Mon Jun  3 09:05:50 CDT 2019
** INFORMATION ** Rows inserted: 2,000. Loading continues... Mon Jun  3 09:05:57 CDT 2019
** INFORMATION ** Rows inserted: 3,000. Loading continues... Mon Jun  3 09:06:03 CDT 2019
** INFORMATION ** Rows inserted: 4,000. Loading continues... Mon Jun  3 09:06:09 CDT 2019
** INFORMATION ** Rows inserted: 5,000. Loading continues... Mon Jun  3 09:06:15 CDT 2019
** INFORMATION ** Rows inserted: 6,000. Loading continues... Mon Jun  3 09:06:24 CDT 2019
** INFORMATION ** Finished file: 6,675 rows read from this file. Mon Jun  3 09:06:36 CDT 2019

Thanks in advance

**Comment by roadrunnerlenny** [comment]
Hey Daniel,

Thanks for your interest in my ETL library! Currently, the Dataflow has no logging implemented that would display the current progress in a data flow. 

But I like the idea, as it could be very helpful. I am currently thinking about having some parameter (e.g. ProgressCount) which could be set either for each object or “globally” in the ControlFlow object as a static property. Then the normal logging mechanism (based on NLog) would be used to log every time when the amount of records defined in ProgressCount is reached in the buffer of a Dataflow component. This way such a progress display could be achieved (NLog can be configured to log either on console, file, database etc.)

I would probably need a couple of days to implement this, release a new version and add some documentation. I would get back to you then.

**Comment by dquinter** [comment]
Thanks, great idea!

You are the best :-)

**Comment by roadrunnerlenny** [comment]
Hi Daniel,

I were able to add some extended logging information to all dataflow components. You will now get log messages that contains the number of processed records.
Here an example how it looks like:
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/6517572/58992258-95fd1900-87ea-11e9-90f5-5a7c7c215198.png">

You can define a threshold when you want to display log message. The default value is 1000, which means that every 1000 records a log message is displayed.

An example how to use the Threshold is here:
https://github.com/roadrunnerlenny/etlbox/blob/81584ad323dcf98f4475041cd6a92160997df48e/ETLBoxTest/src/DataFlow/TestDataFlowLogging.cs#L34-L53

The whole logging is based on Nlog. You have to have a nlog.config file in your directory. More about logging with ETLBox here: (https://etlbox.net/articles/overview_logging.html)

I just released version 1.2.3 on nuget. Please make sure you update you reference to the latests version.
