### ISSUE TITLE
Create table at runtime

### ISSUE THREAD

**Issue by weedkiller** [roadrunnerlenny/etlbox#14]
Hello, I saw your help doc below. I need to be able to insert the types for cols at runtime... can you help

```
CreateTableTask.Create("Staging.NewCustomerOrders", new List<TableColumn>() {
    new TableColumn(name:"key",dataType:"int",allowNulls:false,isPrimaryKey:true, isIdentity:true),
    new TableColumn(name:"value", dataType:"nvarchar(100)",allowNulls:true)
});
```
________________
how can I create this tables cols, and values at run time -- https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.8

```
CreateTableTask.Create("Staging.NewCustomerOrders", new List<TableColumn>() {
 // how can I incorporate the types dynamically from an dictionary or array at runtime
  foreach (KeyValuePair<string, string> keyValue in dict)
  {
       var key = keyValue.Key;
       var value = keyValue.Value;    
           
         new TableColumn(name:key.toString() ,dataType:value.ToString(),allowNulls:false,isPrimaryKey:true, isIdentity:true),
         //or I can get the Type below from string type name https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.8
         new TableColumn(name:key.toString() ,dataType: GetType(value),allowNulls:false,isPrimaryKey:true, isIdentity:true),
           
       ...
       ...          
  }  

});
```

**Comment by roadrunnerlenny** [comment]
You want basically a method that accepts a .NET System.Type and returns a string with the correct DB datatype. 
There is a helper class in ETLBox called `DataTypeConverter`. It already contains static methods that basically takes a string (e.g. "nvarchar(100)") and can convert them into a .NET string-type . 
Unfortunately, there is no method that does it the other way round. You would have to create your own conversion method. 
Perhaps the source code of the DataTypeConverter give you some help how to implment this: 
https://github.com/roadrunnerlenny/etlbox/blob/dev/ETLBox/src/Helper/DataTypeConverter.cs

I can have a deeper look into this in the next couple of days, but at some point you have to have some logic which basically checks if the System.Type is a string and the return "NVARCHAR(MAX)" or something like this. The .NET types won't match exactly to the database types.

I would expect that the method basically compare 
https://github.com/roadrunnerlenny/etlbox/blob/dev/ETLBox/src/Helper/DataTypeConverter.cs

**Comment by weedkiller** [comment]
I have a mechanism to get/convert the data types.

My issue is the _number of columns created/added is dynamic_ and established based on a text file provided/dropped in a folder at run-time. I was hoping for help on _how to add columns/setup and configure (the create table) at run-time_ rather than compile time.

So, I basically setup and tear down staging tables on the fly.

**Comment by roadrunnerlenny** [comment]
Thanks for the clarification.

Perhaps one important thing you should know about the CreateTableTask is that it does not modify a table if the table already exists. (Probably a feature I should add)
Therefor you have to use use the DropTableTask before to drop the table and then recreate it again.

When using the CreateTableTask it will create a table whenever you call Create() - this will internally check if the table already exists and - if the table does not exist- create a new table with the columns provided.

At runtime you can pass any List of TableColumn that you want - so it could be always a different set of columns. But in your Code example you have a foreach statement inside the Create method - that does not work.

Perhaps you create a method called GetTableColumns that returns a List<TableColumn> and accepts as parameter some input like a filename. Depending on the Filename, you could always return a different List.
The ‘CreateTableTask.Create(„staging.tablename“, GetTableColumns(“File1.txt”))’
Would then create a table for File1.txt . You could do the same for other files.

Does that help you with your issue?

**Comment by weedkiller** [comment]
Yes thanks. I see in the foreach how it does not work. 👍 

So can I do something like ` CreateTableTask.Create.Add(new List<TableColumn >())` 
Also does `TableColumn` have an over load construction to create from Sql Col object or simple `<Name, DataType>` Key Value Pair

I can see this could become a widely used feature  ✋

**Comment by roadrunnerlenny** [comment]
Hey Weedkiller,

The static Create method  on CreateTableTask expects either a list of TableColumn objects - or a TableDefinition object which has a property Columns that hold a list of TableColumn. There are currently no other overloads.
If you need to transfer other data objects, I would recommend to use Linq (using System.Linq) and use the Select or Cast methods to do the right transformation. Perhaps you can provide an example what exact object you want to convert in a List of TableColumn and I could help you with the Linq statement, so that you can make your code working. If useful, I could create another overload or Conversion helper.
