### ISSUE TITLE
Support for adding more columns in existing table

### ISSUE THREAD

**Issue by luizhfraraujo** [roadrunnerlenny/etlbox#16]
Hi!

ETLBox have any method to add more columns on a existent table? I create my classs, but when i add more column, the table not changes.

Thanks.
Regards

**Comment by roadrunnerlenny** [comment]
Hi,
thanks for interest in ETLBox. Currently, the `CreateTableTask` will check if a table exists - if the table exists, it will not alter the table.
So you have two options here:
1) Use the `DropTableTask` to drop the table before. It will drop the table only if it exists, so you won't get an error message if you run it without an existing table. After dropping the `CreateTableTask` will create the new table. *Careful:* This will delete all data in your table
2) Use the `SqlTask` to execute the necessary `ALTER TABLE` statements. Here you can add the columns you want to add or change. This will work also work if the table already holds data.

The reason behind that the `CreateTableTask` does not alter a table is that creating the right Alter-statements can be quite complicated (especially if the table holds data). Perhaps a future version will be implementing this feature,  but the current version can't do that.

**Comment by luizhfraraujo** [comment]
Thanks for your response! 
I create a project and use the sqltask. After, i will create a PR with an idea i have to alter table.

Thanks alot

**Comment by roadrunnerlenny** [comment]
Good! Let me know if you encounter any issues.  Looking forward to your PR!

**Comment by roadrunnerlenny** [comment]
Reopened as reference for upcoming PR

**Comment by roadrunnerlenny** [comment]
Were you able to test your idea?
