### ISSUE TITLE
OnCompletion Action for CustomDestination<>

### ISSUE THREAD

**Issue by cyberop5** [roadrunnerlenny/etlbox#18]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is I don't know when i'm done writing to my destination.  

I'm trying to write to an Excel workbook as my destination using EPPlus.  I'm inheriting from the CustomDestination<> class.  I am using the WriteAction property to write out individual rows as they are received.  However, I don't know when the action is done, so I don't know when to save my final workbook.

**Describe the solution you'd like**
I'd like a property added to class CustomDestination<> that's called during Wait().  
`public Action OnCompletion {get;set;}  `
This solution is based on the pattern used in DBDestination<>.

**Describe alternatives you've considered**
I'm currently overwritting Wait() to call an OnCompletion() action I added in my custom class.  
`public new void Wait()
        {
            base.Wait();
            OnCompletion?.Invoke();
        }`
Another option would be to allow Wait to be overridable in base class CustomDestination.  I do not like this option as much because it requires the developer to know the details of the base class's Wait() method (finish current write task, invoke the action, and finally log the results).

**Comment by roadrunnerlenny** [comment]
Hey Matthew,

thanks you for using ETLBox and committing this very detailed feature request. I think that something like a completion action can be very useful, probably not only on the destinations but also on transformations and sources as well. I will have a look into it and create a new version, hopefully in the next couple of days. 
Thank you for the very good input! I will let you know when I made progress.
By the way, do you have the example code for writing into the destination using EPPlus? There is already an ExcelDestination available in ETLBox, but this is depending on another Excel 3rd party library. I am thinking about switching the ExcelSource also using EPPlus.

**Comment by roadrunnerlenny** [comment]
Hi again, 
i just uploaded a new package to nuget - version 1.3.2 will contain the property `public Action OnCompletion` which is called when all data reached the destination. Same implementation as in `DBDestination`.
I had a look to implement this for other Dataflow Tasks, but I probably need to some refactoring first. I'll put it on my list.

**Comment by cyberop5** [comment]
Thanks for adding this feature so quickly. It works great.

My EPPlus class is still a work in progress.  It's supposed to output a nicely formatted workbook. I'll share what I can when I'm done.

I've used EPPlus before with other projects and have nothing but praise for the project.
