### ISSUE TITLE
is etlbox support complex db task？

### ISSUE THREAD

**Issue by sendreams** [roadrunnerlenny/etlbox#23]
i have two database, db1(mysql) and db2(oracle), 
my task is copy the tables in db1 and insert to db2, but there has many details
1、read a table from db1, for example "dbo.table1", the column is:[ id, name, age ]
2、create a hashcode column to db1.table,  the column is:[ id, name, age, hashcode ]
3、read each record and gerenate hashcode by all the column's value,
4、read the table from db2, the column is:[ id, name, age, hashcode ]
5、iterate record by id and compare the hashcode in two record, if hashcode is diff, mean the data is modified, then update the record value to db2's table, otherwise, ignore the record.

is etlbox support all of steps? many thanks。

**Comment by sendreams** [comment]
any more.
i don't want to define Poco class, because we have thousands of tables. and will add new table frequently.

**Comment by roadrunnerlenny** [comment]
Hi,
thanks for your interest in ETLBox. 
Short answer to all of your questions: yes, this can be done with ETLBox. Some parts can be done easy, some parts come with side note.
First of all, the current version (1.4.2) does not support MySql and Oracle with native ADO.NET connection managers. So you need to have an ODBC driver installed to access both databases. I am currently working on a "native" connection manager for MySql, but the ODBC connection should work similar. Only for big amount of data it can be that the native connector does offer a better bulk load integration. 

Regarding your list: 
1) The `DBSource` can read from a database - if you don't create a `Poco`, you will get a string[] array containing the data
2,3) With a `RowTransformation` you can add a column for each row, e.g. a hash code
4,5) You can use a `Lookup` to use data from another table to modify the data in your flow before data is written into the destination table
Alternatively, there is also a `DBMerge` task, which basically finds out which entry is inserted / updated / deleted. But this only works when you have `Poco`, but I can imaging that you could start with a `string[]` and have some object that has the string array and some meta information about the table.

**Comment by sendreams** [comment]
@roadrunnerlenny  very pleasure to see the answer. i'm a newbie for etl, can you please show me some code snip for these step. 
my table almost less then100,000 record, i think the odbc will be ok.
What is the  `DBMerge` task  working principle? is need the table has a time column? so compare the time to check the record state?

many thanks.

**Comment by roadrunnerlenny** [comment]
Hi again, 

sure, I can provide you an example code. 
Have a look at this:
https://github.com/roadrunnerlenny/etlbox/blob/f0005d1c8fe3d3eca29e14b4ca2a9834ae0f98bb/TestsETLBox/src/DataFlowTests/SqlServer/UseCases/UpdateOnHashMatch.cs#L16-L120

Please note that I am currently refactoring my tests, so perhaps some of the constructor which have the Connection as argument won't be there in the current version. 
instead, you can set the ConnectionManager property of the objects (DBSource, DBDestination, SqlTask, etc. all have this property)

It basically does the things you described above. The only thing missing here is to make more "generic" - which means you have to determine how man columns there are in the base table and how to create the update statement.

You can have a look at the DBMerge. But as I wrote, it currently works only with a POCO. Here is an example:
https://github.com/roadrunnerlenny/etlbox/blob/f0005d1c8fe3d3eca29e14b4ca2a9834ae0f98bb/TestsETLBox/src/DataFlowTests/SqlServer/DBMergeTests.cs#L16-L141

Does that help you with your issue?

**Comment by sendreams** [comment]
@roadrunnerlenny hi,thank you for your long answer. 
the first solution, i should do
1. define `TableDefinition` class
2. hard code update, delete,  new sql 

the second solution, i should do 
1. define POCO class
2. implement IMergable interface

Unfortunately, I need to do this for thousands of tables. anyway, i will be test your solution.

**Comment by sendreams** [comment]
i think there has an idea about solution 2, can make a POCO class generator tool which connect to the database and create the POCO class automatic.

**Comment by roadrunnerlenny** [comment]
Hi,

I think you got me wrong. The first solution does use the TableDefinition class. But this is only for example purposes. In your case, when you have thousands of cases, you need to have some kind of logic which creates the correct table defintion dynamically.
So you would some kind of loop that goes over your database, reads the meta data of the table (e.g. using the INFORMATION_SCHEMA in MySql), and adjusts the dataflow accordingly. 
The example above just should demonstrate that you can set up the dataflow *without* a Poco.

**Comment by roadrunnerlenny** [comment]
Or you create your Poco via a generator, that's also possible. But the same logic for creating the Poco classes could be used to modify the dataflow which is using the string array.

**Comment by sendreams** [comment]
do you know any tool can connect popular db and read the tableschma?

**Comment by sendreams** [comment]
solution1 should hard coding the update, delete sql, Does solution 2 also need it?

**Comment by roadrunnerlenny** [comment]
Solution 2 using the `DBMerge` won't let you write Sql. It will generate the necessary SQL code "under the hood". But please note that the DBMerge does not really "update" the entry - in favor of a integrating a bulk insert mechanism, it basically deletes all entries that needs to be updated and insert the new ones. The result is the same, but instead of a real SQL-Update you will end up with a DELETE and  an INSERT statement.

**Comment by roadrunnerlenny** [comment]
I would go for 
```
SELECT table_schema, table_name
FROM INFORMATION_SCHEMA.tables
ORDER BY table_schema, table_name;
```
to get all tables. You can get the columns with 
```
SELECT COLUMN_NAME
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = 'my_database' AND TABLE_NAME = 'my_table';
```
