### ISSUE TITLE
is can support standard net framework?

### ISSUE THREAD

**Issue by sendreams** [roadrunnerlenny/etlbox#24]
the library now support the net core 2.0, cann't be use in standard net framework app. can support in feature?

**Comment by sendreams** [comment]
<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
after change the project file, it's ok now.

**Comment by roadrunnerlenny** [comment]
Version 1.4.0 or higher does support .NET standard and should work with .NET core and .NET and .NET standard projects. Which version are you using for your tests?
