### ISSUE TITLE
Does support mysql database?

### ISSUE THREAD

**Issue by sendreams** [roadrunnerlenny/etlbox#25]
<img width="552" alt="2019-09-04_22-43-35" src="https://user-images.githubusercontent.com/4160051/64265608-ced19900-cf65-11e9-945f-56a07304225e.png">

i have installed mysql odbc connector which can download from here
https://dev.mysql.com/downloads/connector/odbc/5.3.html

this error may be cause by sql syntax error.

my test code is below:
`private` void Button1_Click(object sender, EventArgs e) {

            DBSource source = new DBSource(new OdbcConnectionManager(new OdbcConnectionString("Driver={MySQL ODBC 5.3 Unicode Driver};Server=localhost;Database=pdnw;User=root;Password=***;")), "w_user");
            RowTransformation trans = new RowTransformation(row => {
                LogTask.Info($"Test message: {row[0]}, {row[1]}");  //Log DB is used as this is the ControlFlow.CurrentDBConnection!
                return row;
            });

            DBDestination destination = new DBDestination("w_user") {
                ConnectionManager = new OdbcConnectionManager(new OdbcConnectionString("Driver={MySQL ODBC 5.3 Unicode Driver};Server=localhost;Database=ef6;Uid=root;Pwd=***;"))
            };

            source.LinkTo(trans);
            trans.LinkTo(destination);
            source.Execute();
            destination.Wait();
        }`

**Comment by roadrunnerlenny** [comment]
Hi, 

thanks for filing the bug report.
The issue here is that you pass a tablename and not a table definition. The column names for select / insert statements are determined by querying the meta data information from the server (sys.columns). This works for Sql Server, but apparently not for MySql. 

I will have a look into this (probably i will need to query the INFORMATION_SCHEMA which should exists in Sql Server and MySql)

In the meanwhile, instead of passing the tablename, you can pass a `TableDefinition`:
```
var tableDefinition = new TableDefinition(TableName
                , new List<TableColumn>() {
                new TableColumn("Col1", "INT", allowNulls: false),
                new TableColumn("Col2", "NVARCHAR(100)", allowNulls: true)
            });
var connection = new OdbcConnectionManager(new OdbcConnectionString("Driver={MySQL ODBC 5.3 Unicode Driver};Server=localhost;Database=pdnw;User=root;Password=***;")),

DBSource source = new DBSource()
            {
                SourceTableDefinition = tableDefinition, 
                ConnectionManager = Connection
            };
```
This will force the `DBSource` to use the table definition, and it should not try to query the database for the column names. 

The same applies to the DBDestination. 
```
DBDestination dest = new DBDestination()
            {
                DestinationTableDefinition = tableDefinition, 
                ConnectionManager = Connection
            };
```

**Comment by roadrunnerlenny** [comment]
I just released version. 1.5.0 which includes full SQLite support. I am currently working on MySql support. I will let you when a new version containing this feature is released.

**Comment by roadrunnerlenny** [comment]
Hi, just a quick update on this:
I just released version 1.6.0, which does now fully support SqlServer, SQLite, MySql and Postgres.

**Comment by sendreams** [comment]
@roadrunnerlenny  thanks.  i currently use servicestack to connect serveral type of db. some suggestion for etlbox:
1, separating data access layer, open source implementation can be considered. so you don't need to support so many db types.
2, focus on etl library and enhance custom extension ability

**Comment by roadrunnerlenny** [comment]
Thanks for your feedback. I will think about having an access layer for the database calls. Did you have any particular frameworks in mind?
