### ISSUE TITLE
DBSource -> RowTransformation -> DBDestination

### ISSUE THREAD

**Issue by JPaezHTQA** [roadrunnerlenny/etlbox#3]
Hi all.

Thanks in advance.

I'm trying to get information by SQL Command using DBSource<TOutput>(string Sql), later make a RowTransformation with this information to insert in my DBDestination, but when link the Source with the RowTransformation:

**source.LinkTo(row);**

VS reply with an error, the message is: "Unable to convert: ALE.ETLBox.DataFlow.RowTransformation<int[],EntitiesInfo> to ALE.ETLBox.DataFlow.IDataFlowLinkTarget<EntitiesInfo>".

For more information, here is my code:

  DBSource<EntitiesInfo> source = new DBSource<EntitiesInfo>("Any sql Command");

            RowTransformation<int[], EntitiesInfo> rowT = new RowTransformation<int[], EntitiesInfo>(
                input => new EntitiesInfo
                {
                    X = input[0],
                    X = input[1],
                    X = input[2]
                }
                );

            ControlFlow.CurrentDbConnection = new SqlConnectionManager(new ConnectionString(stringEncoded));
            DBDestination<EntitiesInfo> dest = new DBDestination<EntitiesInfo>("dbo." + EntitiesTemporalTable);
            source.LinkTo(rowT);
            row.LinkTo(dest);        
            source.Execute();
            dest.Wait();
------------------------------------------------------------------
        public class EntitiesInfo
        {
            public int X { get; set; }
            public int X { get; set; }
            public int X { get; set; }
        }

**Comment by JPaezHTQA** [comment]
> Hi all.
> 
> Thanks in advance.
> 
> I'm trying to get information by SQL Command using DBSource(string Sql), later make a RowTransformation with this information to insert in my DBDestination, but when link the Source with the RowTransformation:
> 
> **source.LinkTo(row);**
> 
> VS reply with an error, the message is: "Unable to convert: ALE.ETLBox.DataFlow.RowTransformation<int[],EntitiesInfo> to ALE.ETLBox.DataFlow.IDataFlowLinkTarget".
> 
> For more information, here is my code:
> 
> DBSource source = new DBSource("Any sql Command");
> 
> ```
>         RowTransformation<int[], EntitiesInfo> rowT = new RowTransformation<int[], EntitiesInfo>(
>             input => new EntitiesInfo
>             {
>                 X = input[0],
>                 X = input[1],
>                 X = input[2]
>             }
>             );
> 
>         ControlFlow.CurrentDbConnection = new SqlConnectionManager(new ConnectionString(stringEncoded));
>         DBDestination<EntitiesInfo> dest = new DBDestination<EntitiesInfo>("dbo." + EntitiesTemporalTable);
>         source.LinkTo(rowT);
>         row.LinkTo(dest);        
>         source.Execute();
>         dest.Wait();
> ```
> ```
>     public class EntitiesInfo
>     {
>         public int X { get; set; }
>         public int X { get; set; }
>         public int X { get; set; }
>     }
> ```

**Comment by roadrunnerlenny** [comment]
Hi all, 
seemed you already could solve the issue. Meanwhile I had the chance to write an example code that perhaps helps to clarify things:

```C#
SqlTask.ExecuteNonQuery("Create test table", 
    @"CREATE TABLE dbo.test 
    (Col1 int null, Col2 int null, Col3 int null)"
);
DBSource<EntitiesInfo> source = new DBSource<EntitiesInfo>("SELECT * FROM (VALUES (1,2,3), (4,5,6), (7,8,9)) AS MyTable(Col1,Col2,Col3)");

RowTransformation<EntitiesInfo, EntitiesInfo> rowT = new RowTransformation<EntitiesInfo, EntitiesInfo>(
    input => new EntitiesInfo {
        Col1 = input.Col2+ input.Col3, 
        Col2 = 0,
        Col3 = input.Col1
    } );

ControlFlow.CurrentDbConnection = new SqlConnectionManager(new ConnectionString(ConnectionStringParameter));
DBDestination<EntitiesInfo> dest = new DBDestination<EntitiesInfo>("dbo.test");
source.LinkTo(rowT);
rowT.LinkTo(dest);
source.Execute();
dest.Wait();
```
