### ISSUE TITLE
ETLLogLayoutRenderer database issue

### ISSUE THREAD

**Issue by bencassie** [roadrunnerlenny/etlbox#35]
Hi!

I have been testing the nlog database logging (https://etlbox.net/articles/overview_logging.html) with the ETLLogLayoutRenderer however it appears everything logged using the etllog renderer is null.

I'm not an NLog person so it's not immediately apparent what the issue is.

**Comment by roadrunnerlenny** [comment]
Hi Ben,
I just double checked the tests for logging, but generally the logging mechanism looks good on my machine.
Could you provide some more details?
Do you copy the nlog.config into the output folder?
Can you change the root - element of the nlog.config (which is nlog) into:
```
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwConfigExceptions="true"
      autoReload="true"
      internalLogFile="console-example-internal.log"
      internalLogLevel="Info">
```
Normally, nlog does not throw an error if something goes wrong. With this configuration it will raise an exception and also log it into a file.

**Comment by bencassie** [comment]
Hi,

Thanks for the throwConfigExceptions tip, turns out I was missing the following in my project.

```C#
  <extensions>
    <add assembly="ETLBox"/>
  </extensions>
```
