### ISSUE TITLE
Composite keys on DBMerge

### ISSUE THREAD

**Issue by jonasrdm** [roadrunnerlenny/etlbox#42]
Hi,

I have a question about composite keys. The documentation about merge transformations states as follows:

"Optionally (but highly recommended) you should add the attribute [MergeIdColumnName(...)] to one of your properties of your object. (...) This should be a unique column, e.g. a primary key"

**What if** my source and destination tables does not map a simple primary key, but a composite one? 

I've tryed to map my unique key with the composite properties, IE:
``` c# 
public string UniqueId => $"{prop1}_{prop2}_{prop3}";
```
Yet, unexpectedly it "elected" prop1 as a key, because the following error ocurred:
``` console 
 System.ArgumentException: An item with the same key has already been added. Key: prop1
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at ALE.ETLBox.ConnectionManager.PostgresConnectionManager.BeforeBulkInsert(String tableName)
   at ALE.ETLBox.ControlFlow.DbTask.BulkInsert(ITableData data, String tableName)
   at ALE.ETLBox.DataFlow.DBDestination`1.WriteBatch(TInput[]& data)
   at ALE.ETLBox.DataFlow.DataFlowBatchDestination`1.<InitObjects>b__34_0(TInput[] d)
(...)
```

So the question is: Is ETLBox capable of handling Merge ETL operations on tables with composite keys? And if it is, how can it be done?

Thanks.

**Comment by roadrunnerlenny** [comment]
Hi,

thanks for using ETLBox and your feedback. Right now, the DBMerge is *not* capable of handling tables with composite keys.
The documentation is a little bit unclear here, sorry for this.

I will have a look into this the next couple of days and investigate to extend the DBMerge here, but I currently have no idea if this will be a bigger change or can be implemented straight-forward. I hope I can come back to you in the next couple of days with some progress information.

**Comment by bencassie** [comment]
Just to add comment here, I am in the same position and I've gone with using a staging table to insert the rows and then issue a merge statement to the database to handle the composite key.

**Comment by SaraMoitinho** [comment]
Just to add more to this issue, i've found out that composite keys will result on error not only on DbMerge but on **DbSource** as well.

**Comment by roadrunnerlenny** [comment]
Hi @SaraMoitinho ,

thanks for your feedback. I was able to reproduce the error for the `DBMerge`, but didn't encounter an issue with the `DBSource`.
Could you provide an example to reproduce the bug?
Thank you for your support!

**Comment by roadrunnerlenny** [comment]
Hi @jonasrdm,
I just uploaded a new version to nuget (1.7.1) where the `DBMerge` now should work flawless with tables having composite keys. 
But I had to do some modifications of the component, which I took as a reason to overhaul the whole component. I updated the documentation:
https://etlbox.net/articles/dataflow/dataflow_dbmerge.html

Basically your data object now should inherit from `MergableRow`, and you can use the `IdAttribute` and `CompareColumn` attribute to flag the columns which you want as id and which you want to determine if a matching record needs to be updated.

Please let me now if this solves your issue.
