### ISSUE TITLE
Error retrieving TableDefinition from Postgres when a column is PK and FK

### ISSUE THREAD

**Issue by dhiegobastos** [roadrunnerlenny/etlbox#43]
Hi @roadrunnerlenny 
We've found a problem using DBDestination in a Bulk Insert in table where a column is a primary and foreign key simultaneously. The query used in the ReadTableDefinitionFromPostgres method in the TableDefinition class is returning this field (PK and FK) twice.

**Query example:**
```
**column_name | data_type | is_nullable | serial | primary_key | column_default | collation_name | generation_expression**
codigo_disciplina | integer | 0 | 0 | 1 | null | null | null
codigo_disciplina | integer | 0 | 0 | 1 | null | null | null
codigo_tipo_carga_horaria | integer | 0 | 0 | 1 | null | null | null
descricao_tipo_carga_horaria | character varying | 0 | 0 | 0 | null | null | null
data_inicio | timestamp without time zone | 0 | 0 | 1 | null | null | null
```

This causes a problem on the BeforeBulkInsert method in the PostgresConnectionManager class because it uses the column name as key in the dictionary, causing duplicate keys.

``` C#
DestTableDef = TableDefinition.GetDefinitionFromTableName(tableName, this);
DestinationColumns = new Dictionary<string, TableColumn>();
foreach (var colDef in DestTableDef.Columns)
{
  DestinationColumns.Add(colDef.Name, colDef);
}
```

**Query example with "constraint_name":**
```
column_name | data_type | is_nullable | serial | primary_key | column_default | collation_name | generation_expression | constraint_name
codigo_disciplina | integer | 0 | 0 | 1 | null | null | null | pk_carga_horaria_disciplina
codigo_disciplina | integer | 0 | 0 | 1 | null | null | null | fk_carga_horaria_disciplina
codigo_tipo_carga_horaria | integer | 0 | 0 | 1 | null | null | null | pk_carga_horaria_disciplina
descricao_tipo_carga_horaria | character varying | 0 | 0 | 0 | null | null | null | fk_carga_horaria_disciplina
data_inicio | timestamp without time zone | 0 | 0 | 1 | null | null | null | pk_carga_horaria_disciplina
```

We have thought about two ways to solve this problem, first using the GROUP BY clause and second using the DISTINCT clause. We did tests on Postgres only. Could you validate this problem please? If you prefer, we can make a PR with the solution you agree to.

Thanks,

**Comment by roadrunnerlenny** [comment]
Hi,
thanks you for providing this detailed bug information. I will have a look at this, at first glance it shouldn't be hard to fix, so hopefully I will be able to fix it pretty soon. I would get back to you if I need further assistance here, thanks for offering this.

**Comment by roadrunnerlenny** [comment]
I fixed the bug and I will try to make a new release in the next couple of days.

**Comment by roadrunnerlenny** [comment]
Hi @dhiegobastos ,
I just uploaded version 1.7.1 which should fix this bug.
