### ISSUE TITLE
is there an example of pulling data from a database table to a csv file?

### ISSUE THREAD

**Issue by apocdozer23** [roadrunnerlenny/etlbox#45]
Could you create an example of a sql server source table to a csv file?

**Comment by roadrunnerlenny** [comment]
Hi @apocdozer23 ,
thanks for your interest in ETLBox.

Of course, here is an example code snippet:

```
var connection = new SqlConnectionManager("Data Source=.;Integrated Security=SSPI;");

var source = new DBSource(connection, "TableName");
var dest = new CSVDestination("filename.csv");

source.LinkTo(dest);
source.Execute();
dest.Wait();
```

This is actual a good example for a very basic data flow. I will probably add it to the documentation in the next time.

Regarding performance: ETLBox was designed to work with huge amount of data. Data will be read from the database while it is written into the target - only a small amount of the actual data will be stored in in-memory buffers To improve the throughput you can increase the BatchSize on the CSVDestination - this defines how many objects are buffered in memory before actually writing them into the file.
