### ISSUE TITLE
Timestamps in PostgreSql

### ISSUE THREAD

**Issue by arsen1991** [roadrunnerlenny/etlbox#46]
PostgreSql does not a type 'timestamp' but have types 'timestamp with/without timezone'. GetNETObjectTypeString method checks only 'timestamp'. I have added 'timestamp with/without timezone' checking and it worked.

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 ,
thanks for finding this bug! I will add a test and fix this issue with the next version. I'll let you know when I have released it.

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 ,
 I just released version 1.7.2 which fixes this bug. Appreciate your help!

**Comment by arsen1991** [comment]
Hi @roadrunnerlenny !
Thank you!
