### ISSUE TITLE
Found an issue when getting types from PostgreSql

### ISSUE THREAD

**Issue by arsen1991** [roadrunnerlenny/etlbox#48]
Found an issue in TableDefinition.cs (line 219):     WHEN cols.data_type='character varying' THEN 'varchar('||character_maximum_length||')'.
When  character_maximum_length is null it becomes null as well.

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 ,

thanks for pointing this out! This is small fix, it will included in the next version which probably is released pretty soon.

**Comment by arsen1991** [comment]
Hi @roadrunnerlenny !

Thanks for support!

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 , 
I just release version 1.7..6 (https://www.nuget.org/packages/ETLBox/1.7.6) which contains the fix for this bug. Thank you for reporting this!
