### ISSUE TITLE
Redirect or ignore failed rows

### ISSUE THREAD

**Issue by arsen1991** [roadrunnerlenny/etlbox#49]
Please add a feature to redirect or ignore the row when it fails to insert like in SSIS. For example, load failed rows into the file. See the image below.
![image](https://user-images.githubusercontent.com/58845775/72153027-2b3a3e80-33c6-11ea-8166-bb7e125177f4.png)

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 ,

thanks for your feedback and your idea!
Actually, there is already another issue with more or less the same request:
https://github.com/roadrunnerlenny/etlbox/issues/41
I already started with a first draft implementation, and I was able to implement it with a RowTransformation. 
Hopefully I will be able to continue working on it in the next time, but it probably will take a little while until I have the implementation (&tests) ready for all components. 
Please see issue #41 for the latest commits.

**Comment by roadrunnerlenny** [comment]
Hi @arsen1991 ,

I just released version 1.7.7 (https://www.nuget.org/packages/ETLBox/1.7.7) which now enables you to redirect erroneous records within your flow. See the updated documentation here:
https://etlbox.net/articles/dataflow/dataflow_linking_execution.html#linking-errors
