### ISSUE TITLE
Dynamic Field DataType Discovery during parsing

### ISSUE THREAD

**Issue by papyr** [roadrunnerlenny/etlbox#53]
in my case, the _source CSV data file_ and header content/types change often.

I just need to load the data into a Sql table based on whatever data types there are in the CSV file. Can I auto load the CSV data and datatypes into the DB automatically with ETL box. I saw your expando example but was a little lost how to achieve a high level task

For e.g high level algorithim
```
var etlPrasedFile = EtlBox.Open/parseCSV(someUnknownData.csv)
foreach (var col in etlPrasedFile )
new dataTable.addColumn(etlParsedFile.GetNextHeaderCol)
CreateNewSqlServerTable
LoadDatatoSqlTable??
```

thanks

**Comment by roadrunnerlenny** [comment]
Hi @papyr ,

thanks for your feedback. What you want to achieve can be partly done with ETLBox. 
Let me give you an example. 
Let's assume you a csv file like this:
```
Name;Quantity
ProductA;5
ProductB;3
```
And you have a table in your database that has the following columns:
Id - Col1 - Name - Col2 - Quantity

The following dataflow would load the values of name and Quantity into the correct columns in your database table:

```C#
CSVSource<ExpandoObject> source = new CSVSource<ExpandoObject>("list.csv");
DBDestination<ExpandoObject> dest = new DBDestination<ExpandoObject>(conMan, "table");
source.LinkTo(dest);
source.Execute();
dest.Wait();
``` 

So as you can see, the columns in your csv would be identified by their header nameas and automatically mapped to the right column in your database table. Furthermore, the Quantity column in your database could be of type INTEGER or DECIMAL - ETLBox would automatically convert the csv string into the right datatype. 

Whenever you load a csv file into a database table using ExpandoObject, ETLBox will try to use the header names to find the right column in the destination table and convert it into the destination type. 

The loading of the data can be currently achieved with ETLBox. Now you need to create a destination table dynamically based on your csv file. This is something that can become very tricky and can't be easily done. 
One main problem here is the determination of the data types. A csv file holds by definition only strings - there is no schema definition or something similar that would help you to determine if the data for a column is an Integer or decimal value. So here arrises the first problem.  
However, you can be sure that data from a csv will always fit into a VARCHAR(MAX) (or similar, depending on your database) data type. So one thing you need to do is to determine the name of the header columns in your source file. So you could writer a parse that reads the header columns from your file, and then create the destination table before you start your dataflow. Like this:

```C#
List<string> headerColumns = GetHeaderColumnsFromFile("test.csv");
List<TableColumn> columns = new List<TableColumn>();
foreach (string headerCol in headerColumns) {
    columns.Add(new TableColumn("Id", "VARCHAR(MAX)",allowNulls:true)
}           
CreateTableTask.Create(connectionManager, "tablename", columns);
```

Alternatively (here it becomes a little more tricky) you could use the ExpandoObject created from the `CSVSource` to get the header names. To do so, you need to add a RowTransformation into you dataflow. Your Flow then could look like this:

```C#
bool wasDestinationTableCreated = false;
CSVSource<ExpandoObject> source = new CSVSource<ExpandoObject>("list.csv");
RowTransformation<ExpandoObject,ExpandoObject> trans = new RowTransformation<ExpandoObject,ExpandoObject>(
     row => {
         dynamic r = r as ExpandoObject;
        if (!wasDestinationTableCreate) {
              foreach (KeyValuePair<string, object> kvp in r)
                    AddColumnToDestinationTable(kvp.Key);
               CreateTableBasedOnColumns();
               wasDestinationTableCreated = true;
        }
    }
);
DBDestination<ExpandoObject> dest = new DBDestination<ExpandoObject>(conMan, "table");
source.LinkTo(trans);
trans.LinkTo(dest);
source.Execute();
dest.Wait();
``` 

This flow will take the first row only of your input data and examine the generated ExpandoObject - based on this it will create the destination table. 

*Note*: I haven't tested my code examples yet... But I hope I could support you with my answer.

**Comment by roadrunnerlenny** [comment]
Hi @papyr ,

did the provided answer help?

**Comment by papyr** [comment]
sorry for the delay, I used another lib.

But the sample showed me how to work this. Now, 1) if during reading the file, I can discover types and create tables using a component functionality it would be nice feature.

2) mapping tables/fields from one table in DB1 to table 2 in DB2 -- how is this done?

**Comment by roadrunnerlenny** [comment]
Hi @papyr ,

Regarding 1): type derivation from a csv is something which can't be done easily. Imagin the following data:
```
Name,Quantity
1001,5
2001,3
A3001,100 Pc. 
```
So looking at the first row only would determine an integer value for name and quantity as data. So you would need to parse the whole data set - which is something you probably don't want to do if the csv file becomes quite big. Also, the next time you could a different csv file - so  having VARCHAR(5) for Name could break if the next file would contain a name like "A100050"...

So the question is:  how you design a feature  like this to work with ETLBox? How would you solve this problem? 

Regarding 2: By default, the column is derived by matching names. You can use the ColumnMap attribute to define a different target (or source) column for a property name.
See here: https://etlbox.net/articles/dataflow/dataflow_generic_nongeneric.html#columnmap-attribute

**Comment by papyr** [comment]
Check out [ChoETL](https://github.com/Cinchoo/ChoETL/issues/74), it worked out there, maybe some clues
