### ISSUE TITLE
WebAPI/REST Source

### ISSUE THREAD

**Issue by jpaterson-vdc** [roadrunnerlenny/etlbox#6]
I would like to a WebAPI/REST data source.  I see that "custom" sources can be created, can you provide an example?  I am accessing a REST API from Amazon (Amazon Advertising API) and loading data into a SQL Server database.

**Comment by roadrunnerlenny** [comment]
Hey JPaterson,
i just created a test (in the dev branch) that gives you an example how to consume a Rest API and to store the data in a table.

https://github.com/roadrunnerlenny/etlbox/blob/33933ae2b4a3707bcb4e2f40f3976f7c68932039/ETLBoxTest/src/DataFlowExamples/TestIssue6_CustomSourceWithWS.cs#L24-L80

I hope this code example is helping you. 

I must admit that the CustomSource is kind of tricky to use. If you have improvements or suggestions, feel free to post them here.

**Comment by roadrunnerlenny** [comment]
Hey JPaterson, 

did that solve your issue?
