### ISSUE TITLE
Exception while creating table with long primary key name. (MySQL, MariaDB)

### ISSUE THREAD

**Issue by vladislav-smr** [roadrunnerlenny/etlbox#62]
**Describe the bug**
CreateTableTask can't create table with long primary key name in MySQL MariaDB). Primary key name generated from table name and primary column name. In some cases they can be really long.

**Steps To Reproduce**

    var connectionManager = new MySqlConnectionManager("Server=localhost;User Id=root;Password=root;Database=test;");
    
    var columns = new List<TableColumn>
    {
        new TableColumn
        {
            Name = "ThisIsAReallyLongAndPrettyColumnNameWhichICantChange",
            DataType = "int",
            IsPrimaryKey = true,
        },
        new TableColumn
        {
            Name = "JustRandomColumn",
            DataType = "int"
        },
    };
    
    var tableDefinition = new TableDefinition("ThisIsAReallyLongTableWhichICantChange", columns);
    
    CreateTableTask.Create(connectionManager, tableDefinition);

**Actual behaviour**
I'm getting exception:
*MySql.Data.MySqlClient.MySqlException (0x80004005): Identifier name 'pk_ThisIsAReallyLongTableWhichICantChange_ThisIsAReallyLongAndPrettyColumnNameWhichICantChange' is too long*

**Expected behavior**
Would be great to have control over primary key names. Truncating primary key name in "CreatePrimaryKeyConstraint" method would work as well.

**Comment by roadrunnerlenny** [comment]
Hi @vladislav-smr ,

thanks for reporting the bug. Shouldn't be to complicated to fix, currently I favor the solution that the primary key can be overwritten manually.

**Comment by roadrunnerlenny** [comment]
Just released version 1.8.6 (https://www.nuget.org/packages/ETLBox/1.8.6) where you can specify a primary key constraint name in the TableDefinition - this will prevent the CreateTableTask to auto-generate the constraint name and use the given one.
