### ISSUE TITLE
CreateTableTask TableName & Columns Properties are now read only

### ISSUE THREAD

**Issue by AlexVPerl** [roadrunnerlenny/etlbox#71]
Hi ETLBox team - 

Just updated to latest version and discovered that CreateTableTask TableName & Columns properties are now read only. I went through release notes and didn't see any mention of this change, wondering if perhaps this was by mistake. 

Would it be possible to expose setters for these properties like before?

Thanks.

**Comment by roadrunnerlenny** [comment]
Hi @AlexVPerl ,
thanks for your feedback, and apologies for the late response.
Well, you are right, it was removed more or less by mistake.

The reason behing this is that `CreateTableTask` uses a `TableDefinition` object  to store the columns and the name. So the `TableName` basically return the `TableDefinition.Name`, and Columns just `TableDefinition.Columns`. 

So I will add the missing setter properties again. In the meanwhile, if you want to set these properties, just directly access the TableDefinition. This is basically the same behavior as the missing setter would get. 

Like this:
```
var t = new CreateTableTask();
t.TableDefinition = new TableDefintion("tablename");
t.TableDefinition.Columns = new List<TableColumn>();
```

**Comment by AlexVPerl** [comment]
Great, thanks!

**Comment by roadrunnerlenny** [comment]
Hi Alex, starting with version 1.8.9 the TableName and Columns properties now also have setters again in the CreateTableTask.

**Comment by AlexVPerl** [comment]
Just updated to latest ver. 2.0 - thanks again.
