### ISSUE TITLE
Destination to json file 

### ISSUE THREAD

**Issue by liborpolansky** [roadrunnerlenny/etlbox#9]
Hi,
is there any example how to transfer data to json file? Thank you

**Comment by roadrunnerlenny** [comment]
Hey, thanks for your question. You would need to use a CustomDestination for that. I can prepare an example for that in the next days. 
In the meanwhile, have a look at issue 6 (https://github.com/roadrunnerlenny/etlbox/issues/6) which is showing a similar approach for consuming a web service with the CustomSource.

**Comment by roadrunnerlenny** [comment]
Hi,
sorry for the delay answering you.
Here comes the promised example.
Let's assume you have dataflow where you want to read data from a database table and write them into one json file. Here is how the code could look like:

```C#
public class MySimpleRow {
             public string Value1 { get; set; }
             public int Value2 { get; set; }
}

public void ExampleFlowWritingJson() {
            DBSource<MySimpleRow> source = new DBSource<MySimpleRow>("dbo.table1");

            string json = "[" + Environment.NewLine;
            CustomDestination<MySimpleRow> dest = new CustomDestination<MySimpleRow>(
                row => {
                     json += JsonConvert.SerializeObject(row);
                    }
            );
            source.LinkTo(dest);
            source.Execute();
            dest.Wait();
             
             json += "]";
             File.WriteAllText("result.json", json);

}
```

This example reads all rows from `table1` and write them into a json string variable. When it did read all data, it will write the result into a file called result.json.

**Comment by anlennar** [comment]
In the example above the formatting is a little bit mixed up. 
I added a test case that does the formatting right:
https://github.com/roadrunnerlenny/etlbox/blob/41ff60f6af6daffd85cfb703a3002317ebbd914d/ETLBoxTest/src/DataFlow/TestDataFlowCustomDestination.cs#L56-L76

it basically stores all rows in a List object. When all rows reached the destination, it will then use the JsonConvert method to create the json string.
Be careful when doing this with big data, as all data is stored in memory before writing into a file.

**Comment by anlennar** [comment]
As this was a very good question, I also extended the documentation:
https://etlbox.net/articles/example_json_as_destination.html
Thanks for your feedback!

**Comment by liborpolansky** [comment]
Hi, thank you for quick response! I use it for my solution.

**Comment by roadrunnerlenny** [comment]
Hi, just a quick update here: Version 1.6.1 does now include a `JsonSource` and `JsonDestination`, which can be used to read or write data from/into Json files.

**Comment by apocdozer23** [comment]
Could you include an example where a csv was the target please?

**Comment by apocdozer23** [comment]
> Hi, just a quick update here: Version 1.6.1 does now include a JsonSource and JsonDestination, which can be used to read or write data from/into Json files.  (https://etlbox.net/articles/dataflow_file_sources_destinations.html)

That link is dead. can you fix it?

**Comment by apocdozer23** [comment]
> In the example above the formatting is a little bit mixed up.
> I added a test case that does the formatting right:
> 
>   
>     
>       etlbox/ETLBoxTest/src/DataFlow/TestDataFlowCustomDestination.cs
>     
>     
>         Lines 56 to 76
>       in
>       41ff60f
>     
>     
>     
>     
> 
>         
>           
>            [TestMethod] 
>         
> 
>         
>           
>            public void Table2JsonFile() 
>         
> 
>         
>           
>            { 
>         
> 
>         
>           
>                TableDefinition sourceTableDefinition = CreateSourceTable("test.Source"); 
>         
> 
>         
>           
>             
>         
> 
>         
>           
>                DBSource<MySimpleRow> source = new DBSource<MySimpleRow>(sourceTableDefinition); 
>         
> 
>         
>           
>             
>         
> 
>         
>           
>                List<MySimpleRow> rows = new List<MySimpleRow>(); 
>         
> 
>         
>           
>                CustomDestination<MySimpleRow> dest = new CustomDestination<MySimpleRow>( 
>         
> 
>         
>           
>                    row => { 
>         
> 
>         
>           
>                        rows.Add(row); 
>         
> 
>         
>           
>                    } 
>         
> 
>         
>           
>                ); 
>         
> 
>         
>           
>             
>         
> 
>         
>           
>                source.LinkTo(dest); 
>         
> 
>         
>           
>                source.Execute(); 
>         
> 
>         
>           
>                dest.Wait(); 
>         
> 
>         
>           
>                string json = JsonConvert.SerializeObject(rows, Formatting.Indented); 
>         
> 
>         
>           
>             
>         
> 
>         
>           
>                Assert.AreEqual(json, File.ReadAllText("src/DataFlow/json_tobe.json")); 
>         
> 
>         
>           
>            } 
>         
>     
>   
> 
> 
> it basically stores all rows in a List object. When all rows reached the destination, it will then use the JsonConvert method to create the json string.
> Be careful when doing this with big data, as all data is stored in memory before writing into a file.

Are you saying that ETLBox should not be used on large sets of data?

**Comment by roadrunnerlenny** [comment]
Hi @apocdozer23 ,

fixed the links to the documentation. 

Definitely ETLBox will work very well with large sets of data. 
That should be the whole purpose of an ETL tool, and I can confirm that ETLBox works smooth with huge amounts of data. 

But sometimes things can become a litte more complex. This is when you want to do operations where all your data needs to reside in the memory. 
In ETLBox (and also in other ETL tools) this is the case  when you use "blocking transformations". A simple example for this is the `Sort`. If you want to sort your data, you actually need all of the data loaded to have it properly sorted. This is why the sort component will not continue posting data to linked components until all data has arrived at the sort. When all data was written into the (in-memory) buffer of the sort, it will then sort it and after that start sending the data to the destinations. But you probably already see the issue here: if want to sort 8GB of data, but your application can only get 4GB memory, the data won't fit into the in-memory buffer.

In the example above i used such an in-memory list to create the example.
But actually if you are going to use the `JsonDestination` and `JsonSource`, you don't have to deal with this kind of issue. Only small amount of data will be stored in memory, and data is read from the source while it is written in the destination. 

If you are interested which transformations are "blocking", you can read more about it here:
https://etlbox.net/articles/dataflow/dataflow_transformations.html

**Comment by apocdozer23** [comment]
> Hi @apocdozer23 ,
> fixed the links to the documentation.
> Definitely ETLBox will work very well with large sets of data.
> That should be the whole purpose of an ETL tool, and I can confirm that ETLBox works smooth with huge amounts of data.
> But sometimes things can become a litte more complex. This is when you want to do operations where all your data needs to reside in the memory.
> In ETLBox (and also in other ETL tools) this is the case  when you use "blocking transformations". A simple example for this is the Sort. If you want to sort your data, you actually need all of the data loaded to have it properly sorted. This is why the sort component will not continue posting data to linked components until all data has arrived at the sort. When all data was written into the (in-memory) buffer of the sort, it will then sort it and after that start sending the data to the destinations. But you probably already see the issue here: if want to sort 8GB of data, but your application can only get 4GB memory, the data won't fit into the in-memory buffer.
> In the example above i used such an in-memory list to create the example.
> But actually if you are going to use the JsonDestination and JsonSource, you don't have to deal with this kind of issue. Only small amount of data will be stored in memory, and data is read from the source while it is written in the destination.
> If you are interested which transformations are "blocking", you can read more about it here:
> https://etlbox.net/articles/dataflow/dataflow_transformations.html

could you please include a full example of a database table to csv file?

**Comment by roadrunnerlenny** [comment]
@apocdozer23 ,
please see issue #45 for an example - you asked  the same question there and I already replied you. I will delete the comments from this issue, as they are not related.
